models.py
from app import db
from datetime import datetime
from slugify import slugify


post_tags = db.Table('post_tags', db.Column('post_id',db.ForeignKey('post.id')),
                                    db.Column('tag_id', db.ForeignKey('tag.id')))

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts'), lazy='dynamic')

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return f'<Post id {self.id}, title {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag id {self.id}, name {self.name}>'

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_script import Manager
from flask_migrate import Migrate, MigrateCommand
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView



#App
app = Flask(__name__)
app.config.from_object(Configuration)

#DB config
db = SQLAlchemy(app)
migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

#Admin
from models import Post, Tag
admin = Admin(app)
admin.add_view(ModelView(Post, db.session))
admin.add_view(ModelView(Tag, db.session))

main.py
from app import app
from app import db

from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')


if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, request
from flask import render_template
from flask import redirect
from flask import url_for

from models import Post, Tag
from .forms import PostForm
from app import db

posts = Blueprint('posts', __name__, template_folder='templates')


@posts.route('/')
def posts_list():
    search = request.args.get('search')
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if search:
        posts = Post.query.filter(Post.title.contains(search) | Post.body.contains(search))
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=3)

    return render_template('posts/posts_list.html', posts=posts, pages=pages)


@posts.route('/create', methods=['POST', 'GET', ])
def post_create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        post = Post(title=title, body=body)
        db.session.add(post)
        db.session.commit()

        return redirect(url_for('posts.posts_list'))
    else:
        form = PostForm()
        return render_template('posts/post_create.html', form=form)


@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
def post_edit(slug):
    post = Post.query.filter(Post.slug == slug).first()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))
    else:
        form = PostForm(obj=post)
        return render_template('posts/post_edit.html', post=post, form=form)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    posts = tag.posts
    return render_template('posts/tag_detail.html', posts=posts, tag=tag)

posts/templates/posts/includes/post_card_template.html
<div class="card mt-5">
    <div class="card-header">
        <h5> {{ post.title }} </h5>
    </div>
    <div class="card-body">
        <p class="card-text">{{ post.body }}</p>
        <a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="btn btn-primary">Read</a>
    </div>
    <div class="card-footer text-muted">
        {% for tag in post.tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span
                    class="badge badge-light">{{ tag.name }}</span></a>
        {% endfor %}
    </div>
</div>

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content_title %}
    Hello blueprint

{% endblock %}


{% block content %}
    <br>
    {% for post in posts %}
   <a href="{{ url_for('posts.post_detail', slug=post.slug) }}"><p>{{ post.title }}</p></a>
        {% for tag in post.tags %}
        <span class="badge badge-secondary">{{ tag.name }}</span>
            {% endfor %}
    {% endfor %}

{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}


{% block content %}
    <div class="col-md-6">
        <form action="{{ url_for('posts.post_create') }}" method="post">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label() }}
                    {{ field(class='form-control') }}

                </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary">Create</button>
        </form>
    </div>


{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}


{% endblock %}

{% block content %}
    <div class="tags">

        {% for tag in post.tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge badge-secondary">{{ tag.name }}</span></a>
        {% endfor %}

    </div>
    {{ post.body }}
{% endblock %}

posts/templates/posts/post_edit.html
{% extends 'base.html' %}

{% block title %}
    Edit post {{ post.title }}
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}


{% block content %}
<div class="col-md-6">
    <form action="{{ url_for('posts.post_edit', slug=post.slug) }} " method="post">
            {% for field in form %}
                <div class="form-group">
                    {{ field.label() }}
                    {{ field(class='form-control') }}

                </div>
            {% endfor %}
            <button type="submit" class="btn btn-outline-primary">Save</button>
        </form>
    </div>


{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'base.html' %}

{% block title %}
    Posts list
{% endblock %}

{% block content_title %}
    Post list

{% endblock %}


{% block content %}


    {% for post in pages.items %}

        {% include 'posts/includes/post_card_template.html' %}

    {% endfor %}
    <div class="mt-5">
        <nav aria-label="pagination mt-5">
            <ul class="pagination">
                <li class="page-item {% if not pages.has_prev %} disabled {% endif %} ">
                    <a class="page-link" href="./?page={{ pages.prev_num }}" tabindex="-1"
                       aria-disabled="true">Previous</a>
                </li>
                {% for page in pages.iter_pages() %}
                    <li class="page-item {% if page == pages.page %} active {% endif %}"><a class="page-link"
                                                                                            href="./?page={{ page }}">{{ page }}</a>
                    </li>
                {% endfor %}


                <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
                    <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
                </li>
            </ul>
        </nav>
    </div>

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}


{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for '{{ tag.name }}' tag
{% endblock %}


{% block content %}
    {% for post in posts %}
        {% include 'posts/includes/post_card_template.html' %}
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <a class="navbar-brand" href="{{ url_for('posts.posts_list') }}"><b>maxb02</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('posts.posts_list') }}">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.post_create') }}"  aria-disabled="true">Create Post</a>
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('posts.posts_list') }}">
            <input class="form-control mr-sm-2" type="search" name="search" value="{{ request.args.get('search', '') }}" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

    </div>
</nav>

<div class="container mt-5">
        <h3>{% block content_title %} {% endblock %}</h3>

        {% block content %}
        {% endblock %}

    </div>

</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Flask app
{% endblock %}

{% block content_title %}
    Hello there
{% endblock %}

{% block content %}
    Some content

{% endblock %}